#!/bin/bash

BN=`basename $0`;
DN=`dirname $0`;

arg_list=0;
arg_all=0;
arg_dump_config=0;
arg_configure=0;
arg_collect=0;
arg_synchro=0;
arg_sources=();
arg_verbose=0;
arg_chunk_size=500;
arg_process='';
arg_lock_wait=1800;
for arg in "$@";
do
	case "$arg" in
		"-l" | "--list")
			arg_list=1;
			shift;
			;;
		"-a" | "--all")
			arg_all=1;
			shift;
			;;
		"-h")
			echo "usage: $BN [ --l | --all ]" >&2;
			echo "       $BN <source-name> [ --collect | --synchro ]" >&2;
			exit 1;
			;;
		"-D" | "--dump-config" )
			arg_dump_config=1;
			shift;
			;;
		"-C" | "--configure" )
			arg_configure=1;
			shift;
			;;
		"-c" | "--collect" )
			arg_collect=1;
			shift;
			;;
		"-s" | "--sync" | "--synchro" )
			arg_synchro=1;
			shift;
			;;
		"-v" | "--verbose" )
			arg_verbose=$(($arg_verbose + 1));
			shift;
			;;
		--chunk-size=* )
			arg_chunk_size="${arg#--chunk-size=}";
			shift;
			;;
		--wait=* )
			arg_lock_wait="${arg#--wait=}";
			shift;
			;;
		# PRIVATE
		"---PROCESS" )
			arg_process="$2";
			shift; shift;
			break;
			;;
		-*)
			echo "ERROR: unknown argument '$arg'" >&2;
			exit 1;
			;;
		*)
			arg_sources+=("$arg");
			;;
	esac;
done;

set -u;

function exec_sync() {
	php "$DN/exec.php" "$@";
}

# SYNCHRONISATION SUBPROCESS (expected to be protected by flock)
if [ -n "$arg_process" ];
then
	if [ "$ARG_SYNCHRO" != "1" ];
	then
		mkdir -p "$DATA_DIR";
		rm -f $SOURCE_FILE $DATA_DIR/*.txt $DATA_DIR/*;
		echo "$arg_process" >$SOURCE_FILE;
	else
		read data_src < $SOURCE_FILE;
		if [ "$data_src" != "$arg_process" ];
		then
			echo "$BN: collected data source ($data_src) does not match synchro source ($arg_process) !" >&2;
			exit 1;
		fi;
	fi;
	SQL_COLLECTOR_SOURCE="$arg_process" exec_sync "$@";
	exit $?;
fi;

##########
### MAIN
ARGS=();
if [ "$arg_list" = "1" ];
then
	SQL_COLLECTOR_LIST=1 exec_sync;
	exit $?;
fi;

if [ "$arg_all" = "1" ];
then
	sources=`SQL_COLLECTOR_LIST=1 exec_sync`;

	for src in $sources;
	do
		arg_sources+=("$src");
	done;
fi;

if [ "${#arg_sources[@]}" -gt 1 ] && ([ "$arg_collect" = "1" ] || [ "$arg_synchro" = "1" ]);
then
	echo "$BN: can not combine --collect or --synchro with multiple sources !">&2;
	exit 1;
fi;

## RUN MODE
if [ "$arg_dump_config" = "1" ];
then
	ARGS+=("--dump_config_only");
elif [ "$arg_configure" = "1" ];
then
	ARGS+=("--configure_only");
elif [ "$arg_collect" = "1" ];
then
	ARGS+=("--collect_only");
elif [ "$arg_synchro" = "1" ];
then
	ARGS+=("--synchro_only");
fi;

# process
export DATA_DIR="$DN/data";
export LOCK_FILE="$DATA_DIR/.lock";
export SOURCE_FILE="$DATA_DIR/.source";
for src in "${arg_sources[@]}";
do
	export ARG_SYNCHRO="$arg_synchro";
	export ARG_COLLECT="$arg_collect";

	flock -w "$arg_lock_wait" "$LOCK_FILE" $0 ---PROCESS "$src" "${ARGS[@]}" --console_log_level=$arg_verbose --max_chunk_size=$arg_chunk_size;
done;
